version: '2'

services:
  postgres:
    image: 'mdillon/postgis:10-alpine'
    ports:
      - '5432:5432'
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_PASSWORD=postgres
  back:
    build:
      context: back
    ports:
      - '4000:4000'
    volumes:
      - './back:/app'
    depends_on:
      - 'postgres'
    links:
      - 'postgres'
    entrypoint:
      'sh -c "tail -f /dev/null"'
